services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service

    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # Neon / PostgreSQL
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        value: ep-mute-mud-b1j4fm28.c-5.eu-central-1.aws.neon.tech

      - key: DB_POSTGRESDB_PORT
        value: "5432"

      - key: DB_POSTGRESDB_DATABASE
        value: neondb

      - key: DB_POSTGRESDB_USER
        value: neondb_owner

      - key: DB_POSTGRESDB_PASSWORD
        sync: false

      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"

      # Important: set this manually in Render and keep it forever
      - key: N8N_ENCRYPTION_KEY
        sync: false

      # n8n
      - key: N8N_PROTOCOL
        value: https

      - key: N8N_PORT
        value: "5678"

      - key: PORT
        value: "5678"

      # Timezone
      - key: GENERIC_TIMEZONE
        value: Europe/Berlin

      - key: TZ
        value: Europe/Berlin

      # Limit memory for free Render instance
      - key: NODE_OPTIONS
        value: --max-old-space-size=400